### PR TITLE
bugfix: Rework is_integral check to handle NumPy arrays

### LINKED ISSUE #430: scount/rcount no longer work as np.arrays
Hi! 

I noticed that Scatterv and possibly other functions no longer accept np.arrays as their scount/rcount arguments in master branch.

<details><summary>Example</summary>
<p>

```python
#!/usr/bin/env mpiexec -n 3 python

import numpy as np
from mpi4py import MPI

comm = MPI.COMM_WORLD
assert comm.size == 3

amounts = np.array([3, 4, 2])  # | works as lists
offsets = np.array([0, 3, 7])  # |

if comm.rank == 0:
    data = np.arange(sum(amounts), dtype=float)
else:
    data = None

buffer = np.empty(amounts[comm.rank], dtype=float)

comm.Scatterv(
    [data, amounts, offsets, MPI.DOUBLE],
    [buffer, amounts[comm.rank], MPI.DOUBLE],
    root=0
)

print(f"{comm.rank}, {buffer =}")
```

</p>
</details>

It broke from #356, when function is_integral in src/mpi4py/MPI/msgbuffer.pxi was replaced with PyIndex_Check.
Is it intentional, or can we bring it back?

### PR DESCRIPTION
**Pull request by dalcinl**
Fixes #430

### CODE REVIEW

**Comment by dalcinl** [comment]
@s-valent In here, I'm implementing a slightly simpler version of the original `is_integral()` predicate. Hopefully, this will still play nice with NumPy arrays. Can you imagine of any corner case whether this would not work as expected?

**Comment by dalcinl** [comment]
BTW, I believe the original check was so convoluted simply because of Pyhon 2 oddities. Now that mpi4py is Python 3 only, what I'm doing in this PR may be enough, although I'm not 100% sure.

**Comment by s-valent** [comment]
It seems to be working differently for the case of 0-dimentional arrays (for example, `np.array(2)`), although I'm not sure if it's an issue or not generally

**Comment by dalcinl** [comment]
What do you mean exactly? I'm not following. Do you have any examples where things do not work as expected?

**Comment by s-valent** [comment]
> Do you have any examples where things do not work as expected?

I can't really say it works unexpectedly, just that the behavior changed

```
#!/usr/bin/env mpiexec -n 1 python

import numpy as np
from mpi4py import MPI

comm = MPI.COMM_WORLD

amount = np.array(1)
offset = np.array(0)

data = np.arange(amount, dtype=float)
buffer = np.empty(amount, dtype=float)
comm.Scatterv([data, amount, offset, MPI.DOUBLE], [buffer, amount, MPI.DOUBLE])
```

It's probably fine though, since rcounts and displs as 0-dim arrays are useless

**Comment by dalcinl** [comment]
@s-valent Sorry for the noise. I'm not 100% focused, I missed the very important fact that CI was failing 🤣 . Looks like the only way to go is to reinstate the original implementation of the check. Let see how it goes. If CI passes and you have no further objections/comments, then I'll merge.

**Comment by s-valent** [comment]
No worries, I can never bring myself to be focused)

I have no objections

**Comment by dalcinl** [comment]
@s-valent I added some additional measures to prevent floating dtypes to convert silently as integral (that's how Cython handles things, following C semantics for the cast operator). This may trigger regressions in user codes. However, using floating point values as counts/offsets/indices is something we should not let pass silently and error. Moreover, such automatic conversions are no longer standard behavior in recent Python.

PS: Many thanks for your bug report. This would have been an embarrassing regression for next mpi4py release. No matter how much tests you add, there is always some corner case you are not triggering.

**Pull request merged**
