### PR TITLE
Release 4.0.0

### PR DESCRIPTION
**Pull request by dalcinl**

### CODE REVIEW

**Comment by drew-parsons** [comment]
Have the docs been updated for mpi4py 4?  I'm getting
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/cmd/build.py", line 332, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 242, in __init__
    self.config.setup(self)
  File "/projects/python/git/mpi4py/docs/source/conf.py", line 309, in setup
    module = apidoc.load_module(source)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/python/git/mpi4py/docs/source/apidoc.py", line 538, in load_module
    exec(code, module.__dict__)  # noqa: S102
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 226
    def Datatype.Get_size(self) -> int:
                ^
SyntaxError: expected '('
```

**Comment by dalcinl** [comment]
There have been some updates, yes. Something is definitely off, and it may be related to my doc-generation scripts not working well with older Python versions. What Python version are you running?

**Comment by drew-parsons** [comment]
The old mpi4py version 3.1.6-9 is installed in the system dirs.  Setting PYTHONPATH is intended to get the doc build to catch the new v4 build.

**Comment by dalcinl** [comment]
> The old mpi4py version 3.1.6-9 is installed in the system dirs. Setting PYTHONPATH is intended to get the doc build to catch the new v4 build.

I have the bad feeling that somehow your PYTHONPATH is not being honored. Or maybe you are not using Cython>=3 to build the new mpi4py?

If you look at the docstring of mpi4py methods within a class, the initial line SHOULD NOT start with 'Class.Method', but just `Method`. If that is not the case, you may be either using an old mpi4py or the new mpi4py used Cython 2.

**Comment by drew-parsons** [comment]
It's  cython 3.0.10.  But it is possible that the build is not respecting PYTHONPATH.  Perhaps it's a sphinx problem.  pytest by contrast goes to [some effort](https://docs.pytest.org/en/6.2.x/pythonpath.html) to ensure the order of import from the syspath is controlled.

I'll proceed assuming the old system installation is interfering with the doc build, and think of some workaround.  Ultimately the official build is done on VM so it will probably be fine there.  But I like to be able to test locally before uploading, so I'll see if I can figure out something without having to uninstall the system installation..

**Comment by dalcinl** [comment]
This is the obvious debug tip:

```diff
diff --git a/docs/source/conf.py b/docs/source/conf.py
index ec892352..f219994d 100644
--- a/docs/source/conf.py
+++ b/docs/source/conf.py
@@ -285,6 +285,7 @@ def setup(app):
 
     try:
         from mpi4py import MPI
+        print(MPI)
     except ImportError:
         autodoc_mock_imports.append('mpi4py')
         return
```

Also, make sure to run manually `rm -rf docs/source/reference`, there is an auto generated file in there (`mpi4py.MPI.py`) that maybe is not be refreshed by the build.

**Comment by dalcinl** [comment]
@drew-parsons If you install a recent `tox`, then you can try `tox run -m docs`, just be aware that the output dir is `docs/` (see the end of `tox.ini` for details)

**Comment by drew-parsons** [comment]
> This is the obvious debug tip:

The mystery deepens.  conf.py says its MPI is from the new build
```
Running Sphinx v7.3.7
doc build MPI= <module 'mpi4py.MPI' from '/projects/python/build/mpi4py/.pybuild/cpython3_3.12/build/mpi4py/MPI.cpython-312-x86_64-linux-gnu.so'>
```

**Comment by dalcinl** [comment]
* Did you run `rm -rf docs/source/reference` ?
* If you `print(MPI.Datatype.Get_size.__doc__)`, what do you get?
* FYI, the docs build process generates a file mpi4py.MPI.py in `docs/source/reference`. That file is generated by the `apidoc.py` script in `docs/source`. Looks like the generated code is invalid, but I have no idea way. I cannot reproduce the issue locally, and my CI infrastructure has been working for quite some time.

**Comment by drew-parsons** [comment]
>tox run -m docs

For what it's worth, the tox run finished successfully.  

> Did you run rm -rf docs/source/reference ?

I did not, it was the next thing to try.  But oddly, after the tox run, the doc build (using the debian sphinx invocation) is suddenly proceeding without the error.  I presume tox ran a `rm -rf docs/source/reference`.  I'll check for reproducability with this.

**Comment by dalcinl** [comment]
> I presume tox ran a `rm -rf docs/source/reference`

Yes, it does! Maybe you had there an old file generated from the previous version of mpi4py installed in the system.

**Comment by drew-parsons** [comment]
Eh, yeah, it must have been a glitch from an interrupted build.  The docs are building normally now. Apologies for the distraction.

**Comment by drew-parsons** [comment]
Tests pass locally (amd64, with openmpi 4.1.6), but fail in chroot (pbuilder)
```
testArgsOnlyAtRoot (test_spawn.TestSpawnMultipleSelf.testArgsOnlyAtRoot) ... --------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[10134,2],2]) is on host: sandy
  Process 2 ([[10134,1],0]) is on host: unknown!
  BTLs attempted: vader self

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
[sandy:603951] [[10134,2],0] ORTE_ERROR_LOG: Unreachable in file ../../../ompi/dpm/dpm.c at line 493
[sandy:603953] [[10134,2],2] ORTE_ERROR_LOG: Unreachable in file ../../../ompi/dpm/dpm.c at line 493
[sandy:603952] [[10134,2],1] ORTE_ERROR_LOG: Unreachable in file ../../../ompi/dpm/dpm.c at line 493
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_dpm_dyn_init() failed
  --> Returned "Unreachable" (-12) instead of "Success" (0)
--------------------------------------------------------------------------
[sandy:600890] [[10134,1],0] ORTE_ERROR_LOG: Unreachable in file ../../../ompi/dpm/dpm.c at line 493
ERROR
testCommSpawn (test_spawn.TestSpawnMultipleSelf.testCommSpawn) ... [sandy:603953] *** An error occurred in MPI_Init_thread
[sandy:603953] *** reported by process [664141826,2]
[sandy:603953] *** on a NULL communicator
[sandy:603953] *** Unknown error
[sandy:603953] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[sandy:603953] ***    and potentially your MPI job)
[sandy:600891] 3 more processes have sent help message help-mca-bml-r2.txt / unreachable proc
[sandy:600891] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[sandy:600891] 2 more processes have sent help message help-mpi-runtime.txt / mpi_init:startup:internal-failure
[sandy:600891] 2 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal unknown handle
--------------------------------------------------------------------------
A request has timed out and will therefore fail:

  Operation:  LOOKUP: ../../../orte/orted/pmix/pmix_server_pub.c:345

Your job may terminate as a result of this problem. You may want to
adjust the MCA parameter pmix_server_max_wait and try again. If this
occurred during a connect/accept operation, you can adjust that time
using the pmix_base_exchange_timeout parameter.
--------------------------------------------------------------------------
ERROR
```

**Comment by drew-parsons** [comment]
In any case, the tests pass on the debian build daemons, https://buildd.debian.org/status/package.php?p=mpi4py&suite=experimental

I removed all test skips applied previously in order to get a fresh view of the state of tests across architectures. armhf passed tests (with mpich) without further skips or patching.  Looks like powerpc will need skips reinstated.

**Comment by drew-parsons** [comment]
Curiously the amd64 spawn error was reproduced on the debian buildd building docs (the error occurs running tests, not when building docs.
https://buildd.debian.org/status/fetch.php?pkg=mpi4py&arch=all&ver=4.0.0-1exp1&stamp=1722305597&raw=0

**Comment by dalcinl** [comment]
Open MPI v4.x is know to have buggy/messy spawn support, and things have improved in v5.0.x. You may want to reach to Open MPI folks for help, but for the sake of your mental health my honest advice is: just skip the whole spawn test.
You can `export MPI4PY_TEST_SPAWN=true` as a quick way to skip everything spawn-related.

**Comment by drew-parsons** [comment]
`MPI4PY_TEST_SPAWN=true` makes it easy to do :)
Debian's OpenMPI 5 is currently building in experimental. It will likely be released to Debian unstable in the near future.

**Comment by dalcinl** [comment]
> `MPI4PY_TEST_SPAWN=true` makes it easy to do :)

I had that variable tuned on for more than a year until Open MPI v5.0.x finally fixed all the issue. 
I'm glad I did not remove that code!

**Pull request merged**
