### PR TITLE
typing: Fixes for Py3.7+

### PR DESCRIPTION
**Pull request by dalcinl**
* Some new typing stuff from Py3.10  has to be imported `typing_extensions`.
* Python 3.9 is all OK.
* Python 3.8 has some issues in related to typeshed stubs for `concurrent.futures` (see python/typeshed#7750). Despite this issue, mypy's `stubtest` program can run by passing ignores via allowlist. Typechecking third-party code using mpi4py should work fine (at least, `mypy -p mpi4py` works fine).
* Python 3.7 is all OK.
* Python 3.6 is already EOL. Rather than fixing typing support to support it, I decided to not install `*.pyi` files and the `py.typed` marker file.

PS: I've added exhaustive CI testing for all supported Python versions in GitHub Actions.

### CODE REVIEW

**Comment by dalcinl** [comment]
@henrikhierl As promised, here you have a PR addressing all your concerns. Thanks for your report and suggestions.

**Comment by henrikhierl** [comment]
Thank you for solving the problem so quickly. Works perfectly.

**Comment by leofang** [comment]
All s390x jobs on Travis fail and restarting would not help for some reason... I am looking at the code changes to get some idea.

**Comment by dalcinl** [comment]
> All s390x jobs on Travis fail

Forget about it, these failures are unrelated to the changes, the VMs did not even boot.

@leofang Can I merge?

**Review by leofang — APPROVED** [review]

**Comment by leofang** [comment]
Oops forgot to click the green button yesterday...

**Pull request merged**
